# Generated by Django 4.0 on 2024-03-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_materials',
            name='Thumbnail',
            field=models.FileField(upload_to='thumbnail/'),
        ),
    ]
