# Generated by Django 4.0 on 2024-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_course_materials_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_materials',
            name='pdf',
            field=models.FileField(default='', upload_to='pdf/'),
            preserve_default=False,
        ),
    ]
