# Generated by Django 4.2.3 on 2024-03-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_course_materials_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_level', models.CharField(max_length=100)),
                ('total_question', models.IntegerField(max_length=100)),
                ('total_points', models.IntegerField(max_length=50)),
                ('pass_mark', models.IntegerField(max_length=100)),
                ('course_enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.course_topic')),
            ],
        ),
    ]
