# Generated by Django 4.2.3 on 2024-03-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_assessment_pass_mark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment_add',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assessment_add',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='assessment_add',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='assessment_add',
            name='weight',
        ),
        migrations.AddField(
            model_name='assessment_add',
            name='correct_answer',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment_add',
            name='option_1',
            field=models.CharField(default='2024-04-05', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment_add',
            name='option_2',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment_add',
            name='option_3',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment_add',
            name='option_4',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment_add',
            name='question',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
