# Generated by Django 4.2.3 on 2024-03-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_remove_assessment_add_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_add',
            name='question_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
