# Generated by Django 4.2.3 on 2024-03-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_assessment_add_question_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('Address_line_1', models.CharField(max_length=200)),
                ('Address_line_2', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('faculty_img', models.ImageField(upload_to='faculty/')),
                ('reg_date', models.DateField()),
            ],
        ),
    ]
