# Generated by Django 4.2.3 on 2024-03-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_cartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdata',
            name='stud_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
