# Generated by Django 4.2.3 on 2024-03-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0010_cartdata_stud_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100)),
                ('created_at', models.DateField()),
                ('course_img', models.URLField()),
                ('wishlist_status', models.IntegerField()),
                ('course_enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.course')),
                ('stud_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.stud_reg')),
            ],
        ),
    ]
