# Generated by Django 4.2.3 on 2024-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdata',
            name='username',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
