# Generated by Django 4.2.3 on 2024-03-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0012_cartdata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_materials',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf/'),
        ),
    ]
