# Generated by Django 4.2.3 on 2024-03-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0013_alter_course_materials_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='completedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('course_enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.course_topic')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.stud_reg')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.course_materials')),
            ],
        ),
    ]
