# Generated by Django 4.2.3 on 2024-03-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0015_completedvideos_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_materials',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
