# Generated by Django 4.2.3 on 2024-03-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0016_alter_course_materials_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.IntegerField()),
                ('wrong_answer', models.IntegerField()),
                ('unattend', models.IntegerField()),
                ('final_score', models.IntegerField()),
                ('status', models.IntegerField()),
                ('course_enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.course_topic')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.stud_reg')),
            ],
        ),
    ]
