# Generated by Django 4.2.3 on 2024-03-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0018_finalscore_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscore',
            name='asess_date',
            field=models.DateField(default='2024-03-29'),
            preserve_default=False,
        ),
    ]
