# Generated by Django 4.2.3 on 2024-03-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0019_finalscore_asess_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscore',
            name='percent',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
